//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int idservicio { get; set; }
        public string salud { get; set; }
        public string juridicos { get; set; }
        public string viveres { get; set; }
        public string comida_preparada { get; set; }
        public string empleo { get; set; }
        public string alojamiento_temporal { get; set; }
        public string alojamiento_permanente { get; set; }
        public string educacion { get; set; }
        public string otros { get; set; }
        public int Necesidad_idnecesidad { get; set; }
    
        public virtual Necesidad Necesidad { get; set; }
    }
}
