//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int idSolicitud { get; set; }
        public string servicio { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public int migrante { get; set; }
    }
}
