//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decsoftemigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadColaboradora
    {
        public EntidadColaboradora()
        {
            this.Sector = new HashSet<Sector>();
            this.Necesidad = new HashSet<Necesidad>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public int idEntidadColaboradora { get; set; }
        public string razon_social { get; set; }
        public string NIT { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public string correo { get; set; }
        public string pagina_web { get; set; }
        public int sector { get; set; }
        public int servicio { get; set; }
    
        public virtual ICollection<Sector> Sector { get; set; }
        public virtual ICollection<Necesidad> Necesidad { get; set; }
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
