//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decsoftemigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Migrantes
    {
        public Migrantes()
        {
            this.CiudadActual = new HashSet<CiudadActual>();
            this.SituacionLaboral = new HashSet<SituacionLaboral>();
        }
    
        public int idmigrante { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tipo_documento { get; set; }
        public int No_documento { get; set; }
        public string pais_origen { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string ciudad_actual { get; set; }
        public string situacion_laboral { get; set; }
        public int Solicitud_idSolicitud { get; set; }
    
        public virtual ICollection<CiudadActual> CiudadActual { get; set; }
        public virtual ICollection<SituacionLaboral> SituacionLaboral { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
