//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decsoftemigrant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DecsoftEntitiesconect : DbContext
    {
        public DecsoftEntitiesconect()
            : base("name=DecsoftEntitiesconect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AmigosFamiliares> AmigosFamiliares { get; set; }
        public DbSet<CiudadActual> CiudadActual { get; set; }
        public DbSet<EntidadColaboradora> EntidadColaboradora { get; set; }
        public DbSet<Migrantes> Migrantes { get; set; }
        public DbSet<Necesidad> Necesidad { get; set; }
        public DbSet<Sector> Sector { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<SituacionLaboral> SituacionLaboral { get; set; }
        public DbSet<Solicitud> Solicitud { get; set; }
    }
}
