//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decsoftemigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Necesidad
    {
        public int idnecesidad { get; set; }
        public string salud { get; set; }
        public string alimentacion { get; set; }
        public string empleo { get; set; }
        public string alojamiento_temporal { get; set; }
        public string alojamiento_permanente { get; set; }
        public string educacion { get; set; }
        public string ayuda_legal { get; set; }
        public int EntidadColaboradora_idEntidadColaboradora { get; set; }
    
        public virtual EntidadColaboradora EntidadColaboradora { get; set; }
    }
}
