//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decsoftemigrant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public int idsector { get; set; }
        public string publico { get; set; }
        public string privado { get; set; }
        public string sin_animo_lucro { get; set; }
        public string no_gubernamental { get; set; }
        public string otro { get; set; }
        public int EntidadColaboradora_idEntidadColaboradora { get; set; }
    
        public virtual EntidadColaboradora EntidadColaboradora { get; set; }
    }
}
